
project_id = "ggdndqgufcbuqdbeixvc"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[realtime]
enabled = true

[storage]
enabled = true

[functions]
[functions.create-checkout-session]
verify_jwt = false

[functions.get-mux-transcript]
verify_jwt = false

[functions.update-transcript]
verify_jwt = false

[functions.tokenize]
verify_jwt = false
