// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggdndqgufcbuqdbeixvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdnZG5kcWd1ZmNidXFkYmVpeHZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4NzU2OTEsImV4cCI6MjA1NzQ1MTY5MX0.Gu0o_jicjrapq18sudMNJpu825oR2sX0xtvL_PE0wtI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);